###################################################
#
# file: Makefile
#
# @Author:   Lolas ANASTASIS
# @Version:  18/10/2024
# @email:    csd5197@csd.uoc.gr
#
# Makefile
#
####################################################

CC = gcc
SRC = assignment1.c
TARGET = assignment1

all:
	$(CC) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)
